openapi: 3.0.3
info:
  title: Version Check API
  description: API for checking whether the app version is up to date
  version: 1.0.0

servers:
  - url: http://127.0.0.1:5000
    description: Local development server

paths:
  /version/{v}:
    get:
      summary: Check if app version is up to date
      description: Compare client version with latest server version
      parameters:
        - name: v
          in: path
          required: true
          description: Current app version (float number)
          schema:
            type: number
            format: float
            example: 1.5
      responses:
        '200':
          description: Version comparison result
          content:
            application/json:
              schema:
                type: object
                properties:
                  current_version:
                    type: number
                    format: float
                    example: 1.5
                  latest_version:
                    type: number
                    format: float
                    example: 2.0
                  need_update:
                    type: boolean
                    example: true
        '404':
          description: Invalid version format