openapi: 3.0.3

info:
  title: Task API
  version: 1.0.0
  description: |
    Lab assignment:
    Implement a simple Task Management API using Flask.

servers:
  - url: http://127.0.0.1:5000

tags:
  - name: Lab01
    description: Task Management APIs

paths:

  /tasks:
    get:
      tags: [Lab01]
      summary: Get all tasks
      description: Return all tasks in the system.
      responses:
        "200":
          description: List of tasks
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Task"

    post:
      tags: [Lab01]
      summary: Create a new task
      description: Add a new task using JSON body.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/TaskCreateRequest"
      responses:
        "201":
          description: Task created successfully
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Task"

  /tasks/{id}:
    get:
      tags: [Lab01]
      summary: Get task by ID
      description: Retrieve a task using dynamic routing.
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
          example: 1
      responses:
        "200":
          description: Task found
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Task"
        "404":
          description: Task not found

components:
  schemas:

    Task:
      type: object
      properties:
        id:
          type: integer
        title:
          type: string
        completed:
          type: boolean
      required:
        - id
        - title
        - completed

    TaskCreateRequest:
      type: object
      properties:
        title:
          type: string
      required:
        - title
